name: Docker Build and Tag

on:
  push:
    tags:
      - 'v*.*.*' # Only Trigger on valid semantic version tags
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install Go dependencies
        run: |
          echo "Installing Go dependencies......"
          go mod tidy # Ensure dependencies are resolved
          go mod download

      - name: Run Go tests
        run: |
          echo "Running tests....."
          go test ./... -v
